trigger:
  branches:
    include:
      - develop
      - release
      - master

stages:
  - stage: serverBuild
    displayName: "Server Build"
    dependsOn: []
    pool:
      name: Breakpoint
      demands:
        - yarn
        - msbuild
        - visualstudio
    jobs:
      - job: DevOpsBuild
        displayName: "DevOps Build"
        steps:
          - checkout: self
            persistCredentials: true

          - task: GitVersion@5
            inputs:
              runtime: 'core'

          - task: UpdateBuildNumber@0
            displayName: Update Build Number
            inputs:
              buildNumber: Feliz.PrimeReact $(Build.BuildNumber)

          - task: DotNetCoreCLI@2
            displayName: Build and Pack
            inputs:
              command: pack
              searchPatternPack: "**/Feliz.PrimeReact.fsproj"
              versioningScheme: byEnvVar
              versionEnvVar: "GitVersion.SemVer"
              verbosityPack: normal

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'

          - task: BlueBasher.bluebasher-workitemupdater.bluebasher-workitemupdater.WorkItemUpdater@2
            displayName: WorkItem Updater
            inputs:
              workItemType: Bug,Product Backlog Item
              allWorkItemsSinceLastRelease: true
              workItemState: Coding
              workItemCurrentState: New,Approved,Code Review
              linkBuild: true

          - task: ATP.ATP-GitTag.GitTag.GitTag@5
            displayName: Create version tag in git for master builds
            inputs:
              tag: $(GitVersion.SemVer)
              forceTagCreation: true
              useLightweightTags: true
            condition: eq(variables['Build.SourceBranchName'], 'master')